#!/bin/bash
#!/bin/bash -x

# based on steps found at
#   https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser

#   TODO?
# -----------------------------------
#  - Add tweaks found in
#       https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Tweaks:-Iceweasel
#

echo ""
echo "Setting up boot-to-browser, do not turn off your Pi during this process!"
echo "NOTE: Assumes Pi is configured to boot to command line"
echo ""

# determine directory script is running in
#    via http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Run python script to determine whether plugin is installed
plugin_status_py="$DIR/plugin_status.py"
"$plugin_status_py" touchui
exit_code=$?
if [ $exit_code -eq 0 ]
then
    echo "Saw TouchUI plugin was enabled"
else
    echo "ERROR: TouchUI Plugin not found enabled. (Code: $exit_code)" >&2
    exit 1
fi


# bring system up to date
sudo apt-get update
sudo apt-get -y upgrade


# Install X.org, iceweasel and stuff:
sudo apt-get install -y matchbox xinit x11-xserver-utils unclutter iceweasel


# Get the TouchUI boot files:
wget -P /home/pi/ https://github.com/BillyBlaze/OctoPrint-TouchUI/archive/autostart.zip
# this will create a OctoPrint-TouchUI-autostart directory
unzip -d /home/pi/ /home/pi/autostart.zip


# Copy service file and register it as auto boot:
sudo cp /home/pi/OctoPrint-TouchUI-autostart/touchui.init /etc/init.d/touchui
sudo chmod +x /etc/init.d/touchui
sudo update-rc.d touchui defaults


# this is like `sudo dpkg-reconfigure x11-common` to allow Anybody to run xinit.
sudo sed -i \
    's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config


# can safely remove the downloaded autostart.zip
rm /home/pi/autostart.zip


echo ""
echo "Reboot your Pi to have it boot to Touch UI."
echo "    sudo reboot"
echo ""
