Vagrant.configure("2") do |o|
    # o.vm.box = "octopi-build"
    o.vm.box = "debian/jessie64"
    o.vm.box_url = "debian/jessie64"
    o.vm.synced_folder "../../", "/OctoPi", create:true, type: "nfs"
    o.vm.network :private_network, ip: "192.168.55.55"
    o.vm.provision :shell, :path => "setup.sh"

end
