Vagrant.configure("2") do |o|
    # o.vm.box = "octopi-build"
    o.vm.box = "debian/jessie64"
    o.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    o.vm.synced_folder "../../", "/OctoPi", create:true, type: "nfs", mouunt_options: ['vers=4, nfsvers=4, tcp, noatime']
    o.vm.network :private_network, ip: "192.168.55.55"
    o.vm.provision :shell, :path => "setup.sh"

end
