#!/usr/bin/env bash
set -x
set -e

export LC_ALL=C

source /common.sh
install_cleanup_trap

# Unpack the filesystem changes for the variant
unpack /filesystem/root /

# add-apt-repository ppa:ubuntu-raspi2/ppa -y
apt-get update
apt-get -y --force-yes install libraspberrypi-bin rpi.gpio-common
apt-get clean
apt-get autoremove -y
