#!/bin/sh
### BEGIN INIT INFO
# Provides:          prepare_resize
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: Prepare resize on first boot...
# Description:
### END INIT INFO

. /lib/lsb/init-functions

do_start () {
  . /boot/octopi.txt

  if [ "$perform_resize" != "yes" ]
  then
    log_failure_msg "Resize on boot is disabled"
    exit 1
  fi

  /usr/bin/raspi-config --expand-rootfs >> /var/log/prepare_resize
  /usr/sbin/update-rc.d prepare_resize remove >> /var/log/prepare_resize

  log_success_msg "Resize prepared, rebooting to apply..."
  /sbin/reboot
}

echo "First parameter is $1" >> /var/log/prepare_resize
case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: prepare_resize [start|stop]" >&2
        exit 3
        ;;
esac
