#!/usr/bin/env bash
set -x
set -e
# OctoPI generation script
# Helper script that runs in a Raspbian chroot to create the OctoPI distro
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3

source /common.sh

if [ -n "$OCTOPI_APT_PROXY" ]
then
  echo "Acquire::http { Proxy \"http://$OCTOPI_APT_PROXY\"; };" > /etc/apt/apt.conf.d/02octopi_build_proxy
fi

if [ -n "$OCTOPI_PYPI_INDEX" ]
then
  pip_index_config="[global]\nindex-url = $OCTOPI_PYPI_INDEX"
  easyinstall_index_config="[easy_install]\nindex-url = $OCTOPI_PYPI_INDEX"

  mkdir -p /root/.pip
  echo -e "$pip_index_config" > /root/.pip/pip.conf
  echo -e "$easyinstall_index_config" > /root/.pydistutils.cfg

  mkdir -p /home/pi/.pip
  sudo -u pi echo -e "$pip_index_config" > /home/pi/.pip/pip.conf
  sudo -u pi echo -e "$easyinstall_index_config" > /home/pi/.pydistutils.cfg

  echo "Configured pypi index url $OCTOPI_PYPI_INDEX"
  cat /home/pi/.pip/pip.conf
  cat /home/pi/.pydistutils.cfg
fi

# prevent any installed services from automatically starting (I'm looking at you haproxy)
echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
apt-get update

# in case we are building from a regular raspbian image instead of the lite one...
remove_extra=""
if [ $( is_installed greenfoot ) -eq 1 ];
then
  remove_extra="$remove_extra greenfoot nodered"
fi
apt-get remove -y --purge scratch squeak-plugins-scratch squeak-vm wolfram-engine python-minecraftpi minecraft-pi sonic-pi oracle-java8-jdk bluej libreoffice-common libreoffice-core freepats $remove_extra
apt-get autoremove -y

apt-get -y --force-yes install python2.7 python-virtualenv python-dev git screen libts-bin subversion cmake checkinstall avahi-daemon libavahi-compat-libdnssd1 libffi-dev libssl-dev

echo " - Reinstall iputils-ping"
apt-get install --reinstall iputils-ping


pushd /home/pi

  #build virtualenv
  sudo -u pi virtualenv oprint
  
  # first lets upgrade pip (the shipped version is way too old...)
  sudo -u pi /home/pi/oprint/bin/pip install --upgrade pip

  # we also want pyopenssl so we have a secure SSL context available
  # since that stuff takes ages to compile during build, we do a somewhat dirty
  # trick here by installing the raspbian versions, copying the libs over
  # to our virtualenv and then purging the raspbian versions again
  apt-get -y --force-yes install python-openssl
  if [ $( is_in_apt python-cryptography ) -eq 1 ]; then
    apt-get -y --force-yes install python-cryptography
    from=/usr/lib/python2.7/dist-packages
    to=/home/pi/oprint/lib/python2.7/site-packages
    for pattern in "cffi*" "cryptography*" "OpenSSL*" "ply*" "pycparser*" "pyOpenSSL*" "six*"
    do
      cp -v -r --preserve=mode,timestamps $from/$pattern $to/
    done
    apt-get remove -y --purge python-openssl python-cryptography
  else
    sudo -u pi /home/pi/oprint/bin/pip install cryptography
    apt-get remove -y --purge python-openssl
  fi
  apt-get autoremove -y
  chown -R pi:pi /home/pi/oprint
  sudo -u pi /home/pi/oprint/bin/pip install ndg-httpsclient pyasn1

  # OctoPrint & pyserial
  if [ "$OCTOPI_INCLUDE_OCTOPRINT" == "yes" ]
  then
    echo "--- Installing OctoPrint"

    #pybonjour (for mdns discovery)
    sudo -u pi /home/pi/oprint/bin/pip install https://pybonjour.googlecode.com/files/pybonjour-1.1.1.tar.gz

    #OctoPrint
    chown -R pi:pi OctoPrint
    pushd OctoPrint
      PIP_DEFAULT_TIMEOUT=60 sudo -u pi /home/pi/oprint/bin/python setup.py install
    popd
  fi

  #OctoPiPanel
  if [ "$OCTOPI_INCLUDE_OCTOPIPANEL" == "yes" ]
  then
    echo "--- Installing OctoPiPanel"
    chown -R pi:pi OctoPiPanel
    pushd OctoPiPanel
      sudo -u pi /home/pi/oprint/bin/pip install -r requirements.txt
    popd

    #Add fbcp for TFT screens
    chown -R pi:pi rpi-fbcp
    pushd rpi-fbcp
      sudo -u pi mkdir build
      pushd build
        sudo -u pi cmake ..
        sudo -u pi make
        install fbcp /usr/local/bin/fbcp
        sudo -u pi make clean
      popd
    popd
  fi

  #mjpg-streamer
  if [ "$OCTOPI_INCLUDE_MJPGSTREAMER" == "yes" ]
  then
    echo "--- Installing mjpg-streamer"
    apt-get -y --force-yes --no-install-recommends install libjpeg8-dev imagemagick libav-tools libv4l-dev
    chown -R pi:pi mjpg-streamer
    pushd mjpg-streamer
      mv mjpg-streamer-experimental/* .
      sudo -u pi make
    popd
  fi
  
  #CuraEngine
  if [ "$OCTOPI_INCLUDE_CURAENGINE" == "yes" ]
  then
    echo "--- Installing CuraEngine"
    folder=CuraEngine-$OCTOPI_CURAENGINE_VERSION
    zipfile=$folder.zip
    apt-get -y install gcc-4.7 g++-4.7
    sudo -u pi wget -O$zipfile $OCTOPI_CURAENGINE_ARCHIVE
    sudo -u pi unzip $zipfile
    pushd $folder
      sudo -u pi wget https://gist.githubusercontent.com/foosel/f86d6a729c0187ff8a82/raw/3d4f152b924080f502d887d11269f27a2389d64d/CuraEngine.patch
      sudo -u pi patch < CuraEngine.patch
      sudo -u pi make CXX=g++-4.7 VERSION=$OCTOPI_CURAENGINE_VERSION
      cp build/CuraEngine /usr/local/bin/cura_engine
    popd
    sudo -u pi rm -r $folder $zipfile
  fi

  #setup haproxy for http and https, and webcam
  if [ "$OCTOPI_INCLUDE_HAPROXY" == "yes" ]
  then
    echo "--- Installing haproxy"
    apt-get -y --force-yes install ssl-cert haproxy
    rm /etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/certs/ssl-cert-snakeoil.pem
  fi

  if [ "$OCTOPI_INCLUDE_WIRINGPI" == "yes" ]
  then
    echo "--- Installing WiringPi"
    apt-get install wiringpi
  fi
  
popd

#Make sure user pi has access to serial ports
usermod -a -G tty pi
usermod -a -G dialout pi

# store octopi commit used to build this image
echo "$OCTOPI_COMMIT" > /etc/octopi_commit
echo "$OCTOPI_BUILDBASE" > /etc/octopi_buildbase

# allow pi user to run shutdown and service commands
echo "pi ALL=NOPASSWD: /sbin/shutdown" > /etc/sudoers.d/octoprint-shutdown
echo "pi ALL=NOPASSWD: /sbin/service" > /etc/sudoers.d/octoprint-service

#reach printer by name
echo "$OCTOPI_OVERRIDE_HOSTNAME" > /etc/hostname
sed -i -e "s@raspberrypi@$OCTOPI_OVERRIDE_HOSTNAME@g" /etc/hosts

#make sure users don't run git with sudo, thus breaking permissions, by adding /root/bin to the
#default sudo path and placing a git wrapper script there that checks if it's run as root
sed -i "s@secure_path=\"@secure_path=\"/root/bin:@g" /etc/sudoers
chmod +x /root/bin/git

# enable raspicam
echo "# enable raspicam" >> /boot/config.txt
echo "start_x=1" >> /boot/config.txt
echo "gpu_mem=128" >> /boot/config.txt

# allow network configuration via /boot/octopi-network.txt
sed -i "s@iface wlan0 @iface wlan0-raspbian @g" /etc/network/interfaces
sed -i "s@iface wlan1 @iface wlan1-raspbian @g" /etc/network/interfaces
echo "mapping wlan0" >> /etc/network/interfaces
echo "  script /root/bin/map_iface" >> /etc/network/interfaces
echo "mapping wlan1" >> /etc/network/interfaces
echo "  script /root/bin/map_iface" >> /etc/network/interfaces
echo "source /boot/octopi-network.txt" >> /etc/network/interfaces

# copy /etc/wpa_supplicant/ifupdown.sh to /etc/ifplugd/action.d/ifupdown - for wlan auto reconnect
[ -f /etc/ifplugd/action.d/ifupdown ] && mv /etc/ifplugd/action.d/ifupdown /etc/ifplugd/action.d/ifupdown.original
[ -f /etc/wpa_supplicant/ifupdown.sh ] && ln -s /etc/wpa_supplicant/ifupdown.sh /etc/ifplugd/action.d/ifupdown

#unpack root in the end, so etc file are not overwritten, might need to add two roots int he future
unpack /filesystem/root /

#####################################################################
### setup services

### Disable GUI at start
systemctl_if_exists disable lightdm.service

update-rc.d prepare_resize defaults

### OctoPrint

if [ "$OCTOPI_INCLUDE_OCTOPRINT" == "yes" ]
then
  update-rc.d octoprint defaults 95
else
  # let's remove the configs for system services we don't need
  rm /etc/init.d/octoprint
  rm /etc/default/octoprint
fi

### haproxy

if [ "$OCTOPI_INCLUDE_HAPROXY" == "yes" ]
then
  update-rc.d gencert defaults
else
  # let's remove the configs for system services we don't need
  rm /etc/init.d/gencert

  # also we need to make OctoPrint bind to all interfaces because otherwise
  # it will be unaccessible...
  [ -f /etc/default/octoprint ] && sed -i "s@HOST=127.0.0.1@HOST=0.0.0.0@" /etc/default/octoprint 
fi

### CuraEngine

if [ ! "$OCTOPI_INCLUDE_CURAENGINE" == "yes" ]
then
  # unconfigure the cura engine path in octoprint's config.yaml
  sudo -u pi sed -i -e "s@cura_engine: /usr/local/bin/cura_engine@cura_engine:@g" /home/pi/.octoprint/config.yaml
fi

### mjpg_streamer

if [ "$OCTOPI_INCLUDE_MJPGSTREAMER" == "yes" ]
then
  # make webcamd autostart
  update-rc.d webcamd defaults
else
  rm /etc/logrotate.d/webcamd
  rm /etc/init.d/webcamd
  rm /etc/default/webcamd
  rm /root/bin/webcamd
fi

### OctoPiPanel

if [ ! "$OCTOPI_INCLUDE_OCTOPIPANEL" == "yes" ]
then
  # we don't need the tft setup stuff
  rm /home/pi/scripts/OctoPiPanel
  rm /home/pi/scripts/calibrate-rpi-display
  rm /home/pi/scripts/enable-adafruit-pitft
  rm /home/pi/scripts/enable-rpi-display
  rm /boot/cmdline-pi-tft.txt
  rm /etc/udev/rules.d/95-ads7846.rules
fi

#cleanup
apt-get clean
apt-get autoremove -y

rm -r /usr/sbin/policy-rc.d

if [ -n "$OCTOPI_APT_PROXY" ]
then
  rm -r /etc/apt/apt.conf.d/02octopi_build_proxy
fi

if [ -n "$OCTOPI_PYPI_INDEX" ]
then
  rm -r /root/.pip
  rm -r /root/.pydistutils.cfg
  rm -r /home/pi/.pip/pip.conf
  rm -r /home/pi/.pydistutils.cfg
fi
