#!/usr/bin/env bash
set -x
echo "" > /dev/null

#fix W: Not using locking for nfs mounted lock file /var/cache/apt/archives/lock
mount -o remount,rw /


password=$(perl -e 'printf("%s\n", crypt($ARGV[0], "password"))' "raspberry")
useradd -m -p "${password}" -s /bin/bash pi
usermod -aG video,audio,plugdev,games,netdev,i2c,sudo pi

source /common.sh
install_chroot_fail_on_error_trap

# install dhclient.conf and possibly other files
unpack /filesystem/root /

#cleanup
mkdir -p /var/cache/apt/archives
apt-get clean
apt-get update
apt-get -y --force-yes install avahi-daemon || true
apt-get -y --force-yes install -f
apt-get -y --force-yes install python-pip
pip install virtualenv --upgrade

mkdir -p /var/run/wpa_supplicant
